# Generated by the Chameleon Platform

source 'https://rubygems.org'

ruby '1.9.3'

gem 'rails', '3.2.8'
gem 'unicorn'
gem 'dalli'
gem 'kgio'
gem "haml"
gem "simple_form"
gem 'sass-rails',   '~> 3.2.3'
gem 'compass-rails'
gem 'devise'
gem 'apipie-rails'
gem 'redcarpet'
gem 'rest-client'
gem 'oauth'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '=2.0.3'
gem 'jquery_mobile_rails'


gem 'mongoid', '3.0.6'
# gem 'unicorn'
# gem 'capistrano'

gem 'redis', '2.2.2'
gem 'resque', '1.20.0'

# Gems for extensions that are rails engine gems.
gem 'liquid'

group :development do
  gem 'foreman'
end
